dist: xenial
os: linux
language: node_js
node_js: 'stable'
install:
- npm i -g npm
addons:
  chrome: stable
  firefox: latest
  sonarcloud:
    organization: adobeinc
services:
- xvfb

jobs:
  include:
      - stage: CRON build
        if: type == cron
        script: 
        - npm ci
        - npm run functional:cron:prod
      - stage: PR build
        if: type == pull_request OR type == push
        script:
        - npm ci
        - npm run build:prod
        - npm run functional:ci
        - npm run functional:ci:bs
        - npm run test:saucelabs
      - stage: API/Konductor Build
        if: type == api
        script: 
        - npm ci
        - npm run functional:api

notifications:
  slack: adobedx:AlI4WB2ojGDcqsBEVZ1EGsCR
  email:
    recipients:
      - mowla@adobe.com
      - khoury@adobe.com
      - aahardy@adobe.com
      - alloy-engs@adobe.com
      - ee-konductor-engineering@adobe.com
    on_failure: always
  
before_install:
- stty cols 80